version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-loja
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: loja
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: java-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:mysql://db:3306/loja?allowPublicKeyRetrieval=true&useSSL=false"
      DB_USER: "devuser"
      DB_PASS: "devpassword"
    depends_on:
      - db

volumes:
  db_data: